#!/bin/sh
# Usage:
# ./scripts/cov


MERGER=./node_modules/.bin/lcov-result-merger


# Cleanup & preparation
rm -rf ./lcov ./cov.info
mkdir ./lcov

# Testing
export COLLECT_COVERAGE='true'
npm test

$MOCHA "./test/**/*-test.coffee" >> ./lcov/mocha.info

# Merging LCOV reports
$MERGER './lcov/*.info' ./cov.info

# Output & cleanup
rm -rf ./src-cov ./lcov
